import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Test from '../components/test'
import NftList from '../components/nftList';
import MintNFT from '../components/mintNFT'
import MyNFTs from '../components/myNFTs';
import UploadNFT from '../components/uploadNFT';
import { useReadContract } from 'wagmi';
import { allenNFTExchangeAbi } from '../abis/allenNFTExchangeAbi';
import { contractAddress } from '../utils/address';
import { Address } from 'viem';

const Home: NextPage = () => {

  // 获取市场的所有 NFT
  const { data: marketNFTs } = useReadContract({
    abi: allenNFTExchangeAbi,
    address: contractAddress.marketAddress as Address,
    functionName: 'getAllNFTs',
    args: [],
  })

  

  if (!marketNFTs) { return }

  console.log('marketNFTs', marketNFTs)

  return (
    <div className={styles.container}>
      <Head>
        <title>RainbowKit App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className={styles.main}>
        <p>test  test</p>
        <ConnectButton />
        <hr style={{ width: '100%' }} />
        <MyNFTs marketNFTs={marketNFTs} />
        <hr style={{ width: '100%' }} />
        <MintNFT />
        <hr style={{ width: '100%' }} />
        {/* <UploadNFT /> */}
        {/* <hr style={{ width: '100%' }} /> */}
        <NftList marketNFTs={marketNFTs} />
        <hr style={{ width: '100%' }} />
        {/* <Test /> */}
      </main>

      <footer className={styles.footer}>
        <a href="https://rainbow.me" rel="noopener noreferrer" target="_blank">
          Made with ❤️ by your frens at 🌈
        </a>
      </footer>
    </div>
  );
};

export default Home;
